---
layout: cv
title: Tristan Barlow's CV
---
# Tristan Barlow
51 South 1st East, 83440, Rexburg ID.
(909) 674-3230
tristanbarlowu59@gmail.com

## Summary
Diligent worker, proficient in handling challenging interactions and differences in demanding situations. 
## EDUCATION
Crafton Hills College, Yucaipa CA. (Transferred)
August 2022 - December 2023

Brigham Young University, Rexburg ID.-Enrolled

Enrolled in the Accounting Science Course Minoring in Data Science

January 2024-Current
## Skills

-Problem Solving
-Team Management
-Fundamental communication Skills
-Patience
-Interpersonal Relationships
-Microsoft Excel
-Python
-SQL
-Instagram 


## Community Service

Redlands Food Drive
Deseret Industries 
Local Bishops Storehouse


## EXPERIENCE
1. Student Consultation— Small Business Management, Brigham young University Idaho
Part of a student team that consulted a local Dermatology clinic in Rexburg ID. Helped hire a new social media marketer and streamline his social media advertising, saving him 5,000 dollars a year and generating 5,000 more in revenue. And increased sales by recommending selling products in house, generating an extra few thousand dollars in revenue.

2. BYU-Idaho Lifeguard/Rec Worker/Communications Leader/Lifeguard Instructor/Team Coordinator— BYU Idaho Rec Services, Rexburg. ID
As a lifeguard and rec services worker, I work with customers and practice customer service, setting up, maintaining, and supervising sports any students want to play. As a communication lead, I advertise our services to the students.  As a lifeguard instructor, I help create and run in-services, lead and teach the new guards necessary skills, and am put in a position of leadership. As a team coordinator, I help disseminate important information and problem solve in the moment. I also help build and maintain culture in the workplace.





<!-- ### Footer

Last updated: July 2025 -->
